# Generated by Django 5.0.4 on 2024-04-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='weightingType',
            new_name='weighting_type',
        ),
    ]
