# Generated by Django 5.0.4 on 2024-04-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_weightingtype_client_weighting_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
